### ISSUE TITLE
Weird Error When I Try To Build Textures.

### ISSUE THREAD

**Issue by TheDirtMan** [exa-byte/CCTurtleRemoteController#16]
This is probably my fault entirely and I'm using the wrong jar or something, but I get this error (image attached) and I have no idea how to fix it.

![error](https://github.com/exa-byte/CCTurtleRemoteController/assets/64110828/2b347b53-1b6e-46fd-80c5-e166e51ccfa1)

**Comment by Hellscaped** [comment]
You are correct, you are using the wrong jar. Use the minecraft jar.

**Comment by TheDirtMan** [comment]
Do you know where the minecraft jar is located? I cant seem to find it anywhere.

**Comment by Hellscaped** [comment]
> Do you know where the minecraft jar is located? I cant seem to find it anywhere.

Depends on your launcher. You can download the jars from mcversions.net

**Comment by TheDirtMan** [comment]
Thank you, using a jar from mcversions worked perfectly.
