### ISSUE TITLE
Turtle connected to the localhost but UI shows no turtles.

### ISSUE THREAD

**Issue by TheDirtMan** [exa-byte/CCTurtleRemoteController#17]
I followed all of the steps (I believe correctly) and have the web UI open and it shows an empty dropdown, a text element saying "Last clicked block:" and a discord invite, and when I run the command to connect the turtle to the localhost, it gives the success message and the terminal starts outputting some stuff I don't understand, but there is a problem. In the web UI the dropdown remains empty even though the turtles are supposedly connected. Any help I could get fixing this would be amazing. :)

**Comment by exa-byte** [comment]
We'll need some more information to narrow down your problem. Best ask the question again on discord with some Screenshots and setup details (is it a local or remote Mc server)
